spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/remote_exec_db
    username: app_user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: false
      hibernate.use_sql_comments: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type: OFF